INSERT INTO `warehouses`
(
    `whsName`, `address1`, `city`, `state`, `zip`,
    [#if address2] `address2`, [/if address2]
    [#if lumper] `lumper`, [/if lumper]
    [#if opsMgmt] `ops_mgmt`, [/if opsMgmt]
    [#if genPhone] `gen_phone`, [/if genPhone]
    [#if genEmail] `gen_email`, [/if genEmail]
    [#if genMgr] `gen_mgr`, [/if genMgr]
    [#if genOpen] `gen_open`, [/if genOpen]
    [#if genClose] `gen_close`, [/if genClose]
    [#if genByApt] `gen_by_apt`, [/if genByApt]
    [#if shipPhone] `ship_phone`, [/if shipPhone]
    [#if shipEmail] `ship_email`, [/if shipEmail]
    [#if shipMgr] `ship_mgr`, [/if shipMgr]
    [#if shipOpen] `ship_open`, [/if shipOpen]
    [#if shipClose] `ship_close`, [/if shipClose]
    [#if shipByApt] `ship_by_apt`, [/if shipByApt]
    [#if recPhone] `rec_phone`, [/if recPhone]
    [#if recEmail] `rec_email`, [/if recEmail]
    [#if recMgr] `rec_mgr`, [/if recMgr]
    [#if recOpen] `rec_open`, [/if recOpen]
    [#if recClose] `rec_close`, [/if recClose]
    [#if recByApt] `rec_by_apt` [/if recByApt]
)
VALUES
(
    "{{ name }}", "{{ address1 }}", "{{ city }}", "{{ state }}", "{{ zip }}",
    [#if address2] "{{ address2 }}", [/if address2]
    [#if lumper] "{{ lumper }}", [/if lumper]
    [#if opsMgmt] "{{ ops_mgmt }}", [/if opsMgmt]
    [#if genPhone] "{{ gen_phone }}", [/if genPhone]
    [#if genEmail] "{{ gen_email }}", [/if genEmail]
    [#if genMgr] "{{ gen_mgr }}", [/if genMgr]
    [#if genOpen] "{{ gen_open }}", [/if genOpen]
    [#if genClose] "{{ gen_close }}", [/if genClose]
    [#if genByApt] "{{ gen_by_apt }}", [/if genByApt]
    [#if shipPhone] "{{ ship_phone }}", [/if shipPhone]
    [#if shipEmail] "{{ ship_email }}", [/if shipEmail]
    [#if shipMgr] "{{ ship_mgr }}", [/if shipMgr]
    [#if shipOpen] "{{ ship_open }}", [/if shipOpen]
    [#if shipClose] "{{ ship_close }}", [/if shipClose]
    [#if shipByApt] "{{ ship_by_apt }}", [/if shipByApt]
    [#if recPhone] "{{ rec_phone }}", [/if recPhone]
    [#if recEmail] "{{ rec_email }}", [/if recEmail]
    [#if recMgr] "{{ rec_mgr }}", [/if recMgr]
    [#if recOpen] "{{ rec_open }}", [/if recOpen]
    [#if recClose] "{{ rec_close }}", [/if recClose]
    [#if recByApt] "{{ rec_by_apt }}" [/if recByApt]
);
